ROWS = 15
COLS = 15
SIDE_PANEL = 300
TILE_SIZE = 56
SCREEN_WIDTH = TILE_SIZE * COLS
SCREEN_HEIGHT = TILE_SIZE * ROWS
FPS = 60

# turret constants
TR_ANIMATION_STEPS = 8
TR_ANIMATION_DELAY = 120

# Game properties
SPAWN_RATE = 1500 # time between enemy spawns (ms)
